Eliminate warnings on an unused `py`
Example:

    use cpython::{py_class, PyResult};

    py_class!(class Struct |py| {
        data number: i32;
        def __new__(_cls, n: i32) -> PyResult<Struct> {
            Struct::create_instance(py, n)
        }
        def get_number(&self) -> PyResult<i32> {
            Ok(*self.number(py))
        }
        def get_random(&self) -> PyResult<i32> {
            Ok(4)
        }
    });

Before:

    warning: unused variable: `py`
     --> src/main.rs:3:25
      |
    3 | py_class!(class Struct |py| {
      |                         ^^ help: if this is intentional, prefix it with an underscore: `_py`
      |
      = note: `#[warn(unused_variables)]` on by default

Following the compiler's suggested fix causes the code not to build.

    error[E0425]: cannot find value `py` in this scope
     --> src/main.rs:6:33
      |
    6 |         Struct::create_instance(py, n)
      |                                 ^^ help: a local variable with a similar name exists: `_py`

    error[E0425]: cannot find value `py` in this scope
     --> src/main.rs:9:25
      |
    9 |         Ok(*self.number(py))
      |                         ^^ help: a local variable with a similar name exists: `_py`

After this commit: the original code builds cleanly.